-- Fallback script for table FCL1$Value Entry$437dbf0e-84ff-417a-965d-ed2bb9650972
BEGIN TRANSACTION;

DELETE FROM [FCL1$Value Entry$437dbf0e-84ff-417a-965d-ed2bb9650972];

INSERT INTO [FCL1$Value Entry$437dbf0e-84ff-417a-965d-ed2bb9650972] ([Entry No_], [Item No_], [Posting Date], [Item Ledger Entry Type], [Source No_], [Document No_], [Description], [Location Code], [Inventory Posting Group], [Source Posting Group], [Item Ledger Entry No_], [Valued Quantity], [Item Ledger Entry Quantity], [Invoiced Quantity], [Cost per Unit], [Sales Amount (Actual)], [Salespers__Purch_ Code], [Discount Amount], [User ID], [Source Code], [Applies-to Entry], [Global Dimension 1 Code], [Global Dimension 2 Code], [Source Type], [Cost Amount (Actual)], [Cost Posted to G_L], [Reason Code], [Drop Shipment], [Journal Batch Name], [Gen_ Bus_ Posting Group], [Gen_ Prod_ Posting Group], [Document Date], [External Document No_], [Cost Amount (Actual) (ACY)], [Cost Posted to G_L (ACY)], [Cost per Unit (ACY)], [Document Type], [Document Line No_], [VAT Reporting Date], [Order Type], [Order No_], [Order Line No_], [Expected Cost], [Item Charge No_], [Valued By Average Cost], [Partial Revaluation], [Inventoriable], [Valuation Date], [Entry Type], [Variance Type], [Purchase Amount (Actual)], [Purchase Amount (Expected)], [Sales Amount (Expected)], [Cost Amount (Expected)], [Cost Amount (Non-Invtbl_)], [Cost Amount (Expected) (ACY)], [Cost Amount (Non-Invtbl_)(ACY)], [Expected Cost Posted to G_L], [Exp_ Cost Posted to G_L (ACY)], [Dimension Set ID], [Job No_], [Job Task No_], [Job Ledger Entry No_], [Variant Code], [Adjustment], [Average Cost Exception], [Capacity Ledger Entry No_], [Type], [No_], [Return Reason Code], [$systemId], [$systemCreatedAt], [$systemCreatedBy], [$systemModifiedAt], [$systemModifiedBy])
SELECT [Entry No_], [Item No_], [Posting Date], [Item Ledger Entry Type], [Source No_], [Document No_], [Description], [Location Code], [Inventory Posting Group], [Source Posting Group], [Item Ledger Entry No_], [Valued Quantity], [Item Ledger Entry Quantity], [Invoiced Quantity], [Cost per Unit], [Sales Amount (Actual)], [Salespers__Purch_ Code], [Discount Amount], [User ID], [Source Code], [Applies-to Entry], [Global Dimension 1 Code], [Global Dimension 2 Code], [Source Type], [Cost Amount (Actual)], [Cost Posted to G_L], [Reason Code], [Drop Shipment], [Journal Batch Name], [Gen_ Bus_ Posting Group], [Gen_ Prod_ Posting Group], [Document Date], [External Document No_], [Cost Amount (Actual) (ACY)], [Cost Posted to G_L (ACY)], [Cost per Unit (ACY)], [Document Type], [Document Line No_], [VAT Reporting Date], [Order Type], [Order No_], [Order Line No_], [Expected Cost], [Item Charge No_], [Valued By Average Cost], [Partial Revaluation], [Inventoriable], [Valuation Date], [Entry Type], [Variance Type], [Purchase Amount (Actual)], [Purchase Amount (Expected)], [Sales Amount (Expected)], [Cost Amount (Expected)], [Cost Amount (Non-Invtbl_)], [Cost Amount (Expected) (ACY)], [Cost Amount (Non-Invtbl_)(ACY)], [Expected Cost Posted to G_L], [Exp_ Cost Posted to G_L (ACY)], [Dimension Set ID], [Job No_], [Job Task No_], [Job Ledger Entry No_], [Variant Code], [Adjustment], [Average Cost Exception], [Capacity Ledger Entry No_], [Type], [No_], [Return Reason Code], [$systemId], [$systemCreatedAt], [$systemCreatedBy], [$systemModifiedAt], [$systemModifiedBy]
FROM [FCL].[dbo].[FCL1$Value Entry$437dbf0e-84ff-417a-965d-ed2bb9650972];

COMMIT;