-- Fallback script for table FCL1$Prod_ Order Line$437dbf0e-84ff-417a-965d-ed2bb9650972
BEGIN TRANSACTION;

DELETE FROM [FCL1$Prod_ Order Line$437dbf0e-84ff-417a-965d-ed2bb9650972];

INSERT INTO [FCL1$Prod_ Order Line$437dbf0e-84ff-417a-965d-ed2bb9650972] ([Status], [Prod_ Order No_], [Line No_], [Item No_], [Variant Code], [Description], [Description 2], [Location Code], [Shortcut Dimension 1 Code], [Shortcut Dimension 2 Code], [Bin Code], [Quantity], [Finished Quantity], [Remaining Quantity], [Scrap _], [Due Date], [Starting Date], [Starting Time], [Ending Date], [Ending Time], [Planning Level Code], [Priority], [Production BOM No_], [Routing No_], [Inventory Posting Group], [Routing Reference No_], [Unit Cost], [Cost Amount], [Qty_ Rounding Precision], [Qty_ Rounding Precision (Base)], [Unit of Measure Code], [Quantity (Base)], [Finished Qty_ (Base)], [Remaining Qty_ (Base)], [Starting Date-Time], [Ending Date-Time], [Dimension Set ID], [Cost Amount (ACY)], [Unit Cost (ACY)], [Production BOM Version Code], [Routing Version Code], [Routing Type], [Qty_ per Unit of Measure], [MPS Order], [Planning Flexibility], [Indirect Cost _], [Overhead Rate], [$systemId], [$systemCreatedAt], [$systemCreatedBy], [$systemModifiedAt], [$systemModifiedBy])
SELECT [Status], [Prod_ Order No_], [Line No_], [Item No_], [Variant Code], [Description], [Description 2], [Location Code], [Shortcut Dimension 1 Code], [Shortcut Dimension 2 Code], [Bin Code], [Quantity], [Finished Quantity], [Remaining Quantity], [Scrap _], [Due Date], [Starting Date], [Starting Time], [Ending Date], [Ending Time], [Planning Level Code], [Priority], [Production BOM No_], [Routing No_], [Inventory Posting Group], [Routing Reference No_], [Unit Cost], [Cost Amount], [Qty_ Rounding Precision], [Qty_ Rounding Precision (Base)], [Unit of Measure Code], [Quantity (Base)], [Finished Qty_ (Base)], [Remaining Qty_ (Base)], [Starting Date-Time], [Ending Date-Time], [Dimension Set ID], [Cost Amount (ACY)], [Unit Cost (ACY)], [Production BOM Version Code], [Routing Version Code], [Routing Type], [Qty_ per Unit of Measure], [MPS Order], [Planning Flexibility], [Indirect Cost _], [Overhead Rate], [$systemId], [$systemCreatedAt], [$systemCreatedBy], [$systemModifiedAt], [$systemModifiedBy]
FROM [FCL].[dbo].[FCL1$Prod_ Order Line$437dbf0e-84ff-417a-965d-ed2bb9650972];

COMMIT;