-- Fallback script for table FCL1$Sales Invoice Entity Aggregate$437dbf0e-84ff-417a-965d-ed2bb9650972
BEGIN TRANSACTION;

DELETE FROM [FCL1$Sales Invoice Entity Aggregate$437dbf0e-84ff-417a-965d-ed2bb9650972];

INSERT INTO [FCL1$Sales Invoice Entity Aggregate$437dbf0e-84ff-417a-965d-ed2bb9650972] ([No_], [Posted], [Document Type], [Sell-to Customer No_], [Bill-to Customer No_], [Bill-to Name], [Bill-to Address], [Bill-to Address 2], [Bill-to City], [Bill-to Contact], [Your Reference], [Ship-to Code], [Ship-to Name], [Ship-to Address], [Ship-to Address 2], [Ship-to City], [Ship-to Contact], [Posting Date], [Payment Terms Code], [Due Date], [Shipment Method Code], [Shortcut Dimension 1 Code], [Shortcut Dimension 2 Code], [Customer Posting Group], [Currency Code], [Prices Including VAT], [Salesperson Code], [Order No_], [Amount], [Amount Including VAT], [VAT Registration No_], [Sell-to Customer Name], [Sell-to Address], [Sell-to Address 2], [Sell-to City], [Sell-to Contact], [Bill-to Post Code], [Bill-to County], [Bill-to Country_Region Code], [Sell-to Post Code], [Sell-to County], [Sell-to Country_Region Code], [Ship-to Post Code], [Ship-to County], [Ship-to Country_Region Code], [Document Date], [External Document No_], [Tax Area Code], [Tax Liable], [VAT Bus_ Posting Group], [Invoice Discount Calculation], [Invoice Discount Value], [IsTest], [Sell-to Phone No_], [Sell-to E-Mail], [Cust_ Ledger Entry No_], [Invoice Discount Amount], [Dispute Status], [Promised Pay Date], [Sell-to Contact No_], [Id], [Dispute Status Id], [Total Tax Amount], [Status], [Subtotal Amount], [Discount Applied Before Tax], [Last Modified Date Time], [Customer Id], [Order Id], [Contact Graph Id], [Currency Id], [Payment Terms Id], [Shipment Method Id], [Tax Area ID], [Bill-to Customer Id], [$systemId], [$systemCreatedAt], [$systemCreatedBy], [$systemModifiedAt], [$systemModifiedBy])
SELECT [No_], [Posted], [Document Type], [Sell-to Customer No_], [Bill-to Customer No_], [Bill-to Name], [Bill-to Address], [Bill-to Address 2], [Bill-to City], [Bill-to Contact], [Your Reference], [Ship-to Code], [Ship-to Name], [Ship-to Address], [Ship-to Address 2], [Ship-to City], [Ship-to Contact], [Posting Date], [Payment Terms Code], [Due Date], [Shipment Method Code], [Shortcut Dimension 1 Code], [Shortcut Dimension 2 Code], [Customer Posting Group], [Currency Code], [Prices Including VAT], [Salesperson Code], [Order No_], [Amount], [Amount Including VAT], [VAT Registration No_], [Sell-to Customer Name], [Sell-to Address], [Sell-to Address 2], [Sell-to City], [Sell-to Contact], [Bill-to Post Code], [Bill-to County], [Bill-to Country_Region Code], [Sell-to Post Code], [Sell-to County], [Sell-to Country_Region Code], [Ship-to Post Code], [Ship-to County], [Ship-to Country_Region Code], [Document Date], [External Document No_], [Tax Area Code], [Tax Liable], [VAT Bus_ Posting Group], [Invoice Discount Calculation], [Invoice Discount Value], [IsTest], [Sell-to Phone No_], [Sell-to E-Mail], [Cust_ Ledger Entry No_], [Invoice Discount Amount], [Dispute Status], [Promised Pay Date], [Sell-to Contact No_], [Id], [Dispute Status Id], [Total Tax Amount], [Status], [Subtotal Amount], [Discount Applied Before Tax], [Last Modified Date Time], [Customer Id], [Order Id], [Contact Graph Id], [Currency Id], [Payment Terms Id], [Shipment Method Id], [Tax Area ID], [Bill-to Customer Id], [$systemId], [$systemCreatedAt], [$systemCreatedBy], [$systemModifiedAt], [$systemModifiedBy]
FROM [FCL].[dbo].[FCL1$Sales Invoice Entity Aggregate$437dbf0e-84ff-417a-965d-ed2bb9650972];

COMMIT;