-- Fallback script for table FCL1$VAT Entry$437dbf0e-84ff-417a-965d-ed2bb9650972
BEGIN TRANSACTION;

DELETE FROM [FCL1$VAT Entry$437dbf0e-84ff-417a-965d-ed2bb9650972];

INSERT INTO [FCL1$VAT Entry$437dbf0e-84ff-417a-965d-ed2bb9650972] ([Entry No_], [Gen_ Bus_ Posting Group], [Gen_ Prod_ Posting Group], [Posting Date], [Document No_], [Document Type], [Type], [Base], [Amount], [VAT Calculation Type], [Bill-to_Pay-to No_], [EU 3-Party Trade], [User ID], [Source Code], [Reason Code], [Closed by Entry No_], [Closed], [Country_Region Code], [Internal Ref_ No_], [Transaction No_], [Unrealized Amount], [Unrealized Base], [Remaining Unrealized Amount], [Remaining Unrealized Base], [External Document No_], [No_ Series], [Tax Area Code], [Tax Liable], [Tax Group Code], [Use Tax], [Tax Jurisdiction Code], [Tax Group Used], [Tax Type], [Tax on Tax], [Sales Tax Connection No_], [Unrealized VAT Entry No_], [VAT Bus_ Posting Group], [VAT Prod_ Posting Group], [Additional-Currency Amount], [Additional-Currency Base], [Add_-Currency Unrealized Amt_], [Add_-Currency Unrealized Base], [VAT Base Discount _], [Add_-Curr_ Rem_ Unreal_ Amount], [Add_-Curr_ Rem_ Unreal_ Base], [VAT Difference], [Add_-Curr_ VAT Difference], [Ship-to_Order Address Code], [Document Date], [VAT Registration No_], [Reversed], [Reversed by Entry No_], [Reversed Entry No_], [EU Service], [Base Before Pmt_ Disc_], [Source Currency VAT Amount], [Source Currency VAT Base], [Source Currency Code], [Source Currency Factor], [Journal Templ_ Name], [Journal Batch Name], [Realized Amount], [Realized Base], [Add_-Curr_ Realized Amount], [Add_-Curr_ Realized Base], [G_L Acc_ No_], [VAT Reporting Date], [Non-Deductible VAT _], [Non-Deductible VAT Base], [Non-Deductible VAT Amount], [Non-Deductible VAT Base ACY], [Non-Deductible VAT Amount ACY], [Non-Deductible VAT Diff_], [Non-Deductible VAT Diff_ ACY], [$systemId], [$systemCreatedAt], [$systemCreatedBy], [$systemModifiedAt], [$systemModifiedBy])
SELECT [Entry No_], [Gen_ Bus_ Posting Group], [Gen_ Prod_ Posting Group], [Posting Date], [Document No_], [Document Type], [Type], [Base], [Amount], [VAT Calculation Type], [Bill-to_Pay-to No_], [EU 3-Party Trade], [User ID], [Source Code], [Reason Code], [Closed by Entry No_], [Closed], [Country_Region Code], [Internal Ref_ No_], [Transaction No_], [Unrealized Amount], [Unrealized Base], [Remaining Unrealized Amount], [Remaining Unrealized Base], [External Document No_], [No_ Series], [Tax Area Code], [Tax Liable], [Tax Group Code], [Use Tax], [Tax Jurisdiction Code], [Tax Group Used], [Tax Type], [Tax on Tax], [Sales Tax Connection No_], [Unrealized VAT Entry No_], [VAT Bus_ Posting Group], [VAT Prod_ Posting Group], [Additional-Currency Amount], [Additional-Currency Base], [Add_-Currency Unrealized Amt_], [Add_-Currency Unrealized Base], [VAT Base Discount _], [Add_-Curr_ Rem_ Unreal_ Amount], [Add_-Curr_ Rem_ Unreal_ Base], [VAT Difference], [Add_-Curr_ VAT Difference], [Ship-to_Order Address Code], [Document Date], [VAT Registration No_], [Reversed], [Reversed by Entry No_], [Reversed Entry No_], [EU Service], [Base Before Pmt_ Disc_], [Source Currency VAT Amount], [Source Currency VAT Base], [Source Currency Code], [Source Currency Factor], [Journal Templ_ Name], [Journal Batch Name], [Realized Amount], [Realized Base], [Add_-Curr_ Realized Amount], [Add_-Curr_ Realized Base], [G_L Acc_ No_], [VAT Reporting Date], [Non-Deductible VAT _], [Non-Deductible VAT Base], [Non-Deductible VAT Amount], [Non-Deductible VAT Base ACY], [Non-Deductible VAT Amount ACY], [Non-Deductible VAT Diff_], [Non-Deductible VAT Diff_ ACY], [$systemId], [$systemCreatedAt], [$systemCreatedBy], [$systemModifiedAt], [$systemModifiedBy]
FROM [FCL].[dbo].[FCL1$VAT Entry$437dbf0e-84ff-417a-965d-ed2bb9650972];

COMMIT;