-- Fallback script for table FCL1$Sales Invoice Line$437dbf0e-84ff-417a-965d-ed2bb9650972
BEGIN TRANSACTION;

DELETE FROM [FCL1$Sales Invoice Line$437dbf0e-84ff-417a-965d-ed2bb9650972];

INSERT INTO [FCL1$Sales Invoice Line$437dbf0e-84ff-417a-965d-ed2bb9650972] ([Document No_], [Line No_], [Sell-to Customer No_], [Type], [No_], [Location Code], [Posting Group], [Shipment Date], [Description], [Description 2], [Unit of Measure], [Quantity], [Unit Price], [Unit Cost (LCY)], [VAT _], [Line Discount _], [Line Discount Amount], [Amount], [Amount Including VAT], [Allow Invoice Disc_], [Gross Weight], [Net Weight], [Units per Parcel], [Unit Volume], [Appl_-to Item Entry], [Shortcut Dimension 1 Code], [Shortcut Dimension 2 Code], [Customer Price Group], [Job No_], [Work Type Code], [Shipment No_], [Shipment Line No_], [Order No_], [Order Line No_], [Bill-to Customer No_], [Inv_ Discount Amount], [Drop Shipment], [Gen_ Bus_ Posting Group], [Gen_ Prod_ Posting Group], [VAT Calculation Type], [Transaction Type], [Transport Method], [Attached to Line No_], [Exit Point], [Area], [Transaction Specification], [Tax Category], [Tax Area Code], [Tax Liable], [Tax Group Code], [VAT Clause Code], [VAT Bus_ Posting Group], [VAT Prod_ Posting Group], [Blanket Order No_], [Blanket Order Line No_], [VAT Base Amount], [Unit Cost], [System-Created Entry], [Line Amount], [VAT Difference], [VAT Identifier], [IC Partner Ref_ Type], [IC Partner Reference], [Prepayment Line], [IC Partner Code], [Posting Date], [IC Item Reference No_], [Pmt_ Discount Amount], [Line Discount Calculation], [Dimension Set ID], [Job Task No_], [Job Contract Entry No_], [Deferral Code], [Allocation Account No_], [Variant Code], [Bin Code], [Qty_ per Unit of Measure], [Unit of Measure Code], [Quantity (Base)], [FA Posting Date], [Depreciation Book Code], [Depr_ until FA Posting Date], [Duplicate in Depreciation Book], [Use Duplication List], [Responsibility Center], [Item Category Code], [Nonstock], [Purchasing Code], [Item Reference No_], [Item Reference Unit of Measure], [Item Reference Type], [Item Reference Type No_], [Appl_-from Item Entry], [Return Reason Code], [Price Calculation Method], [Allow Line Disc_], [Customer Disc_ Group], [Price description], [$systemId], [$systemCreatedAt], [$systemCreatedBy], [$systemModifiedAt], [$systemModifiedBy])
SELECT [Document No_], [Line No_], [Sell-to Customer No_], [Type], [No_], [Location Code], [Posting Group], [Shipment Date], [Description], [Description 2], [Unit of Measure], [Quantity], [Unit Price], [Unit Cost (LCY)], [VAT _], [Line Discount _], [Line Discount Amount], [Amount], [Amount Including VAT], [Allow Invoice Disc_], [Gross Weight], [Net Weight], [Units per Parcel], [Unit Volume], [Appl_-to Item Entry], [Shortcut Dimension 1 Code], [Shortcut Dimension 2 Code], [Customer Price Group], [Job No_], [Work Type Code], [Shipment No_], [Shipment Line No_], [Order No_], [Order Line No_], [Bill-to Customer No_], [Inv_ Discount Amount], [Drop Shipment], [Gen_ Bus_ Posting Group], [Gen_ Prod_ Posting Group], [VAT Calculation Type], [Transaction Type], [Transport Method], [Attached to Line No_], [Exit Point], [Area], [Transaction Specification], [Tax Category], [Tax Area Code], [Tax Liable], [Tax Group Code], [VAT Clause Code], [VAT Bus_ Posting Group], [VAT Prod_ Posting Group], [Blanket Order No_], [Blanket Order Line No_], [VAT Base Amount], [Unit Cost], [System-Created Entry], [Line Amount], [VAT Difference], [VAT Identifier], [IC Partner Ref_ Type], [IC Partner Reference], [Prepayment Line], [IC Partner Code], [Posting Date], [IC Item Reference No_], [Pmt_ Discount Amount], [Line Discount Calculation], [Dimension Set ID], [Job Task No_], [Job Contract Entry No_], [Deferral Code], [Allocation Account No_], [Variant Code], [Bin Code], [Qty_ per Unit of Measure], [Unit of Measure Code], [Quantity (Base)], [FA Posting Date], [Depreciation Book Code], [Depr_ until FA Posting Date], [Duplicate in Depreciation Book], [Use Duplication List], [Responsibility Center], [Item Category Code], [Nonstock], [Purchasing Code], [Item Reference No_], [Item Reference Unit of Measure], [Item Reference Type], [Item Reference Type No_], [Appl_-from Item Entry], [Return Reason Code], [Price Calculation Method], [Allow Line Disc_], [Customer Disc_ Group], [Price description], [$systemId], [$systemCreatedAt], [$systemCreatedBy], [$systemModifiedAt], [$systemModifiedBy]
FROM [FCL].[dbo].[FCL1$Sales Invoice Line$437dbf0e-84ff-417a-965d-ed2bb9650972];

COMMIT;